# Generated by Django 4.0.1 on 2022-01-15 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0002_alter_medication_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Z-_]*$', 'Only uppercase letters, dash (-) underscores (_) allowed.')]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Z-_]*$', 'Only uppercase letters, dash (-) underscores (_) allowed.')]),
        ),
    ]
