# Generated by Django 4.0.1 on 2022-01-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0003_alter_medication_code_alter_medication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
