# Generated by Django 4.0.1 on 2022-01-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0005_alter_drone_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='medications',
        ),
    ]
