# Generated by Django 4.0.1 on 2022-01-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0006_remove_drone_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='medications',
            field=models.ManyToManyField(blank=True, to='drone_api.Medication'),
        ),
    ]
