# Generated by Django 4.0.1 on 2022-01-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0008_remove_drone_medications_medication_drone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryLevelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_serial_number', models.CharField(max_length=255)),
                ('battery_level', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drone_api.drone')),
            ],
        ),
    ]
