# Generated by Django 4.0.1 on 2022-01-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_api', '0009_batterylevellog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterylevellog',
            name='drone_serial_number',
        ),
        migrations.AddField(
            model_name='batterylevellog',
            name='serial_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='batterylevellog',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
